export default {
  name: 'workExperience',
  title: 'Work Experience',
  type: 'document',
  fields: [
    {
      name: 'role',
      title: 'Role / Position',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'company',
      title: 'Company Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'companyUrl',
      title: 'Company Website',
      type: 'url',
    },
    {
      name: 'companyLogo',
      title: 'Company Logo',
      type: 'image',
      options: { hotspot: true },
      description: 'Optional logo to display alongside the experience',
    },
    {
      name: 'location',
      title: 'Location',
      type: 'string',
      description: 'e.g., "Dubai, UAE"',
    },
    {
      name: 'startYear',
      title: 'Start Year',
      type: 'number',
      description: 'e.g., 2019',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'endYear',
      title: 'End Year',
      type: 'number',
      description: 'Leave empty for current position',
    },
    {
      name: 'isCurrent',
      title: 'Current Position',
      type: 'boolean',
      description: 'Check if this is your current job',
      initialValue: false,
    },
    {
      name: 'startDate',
      title: 'Start Date (Display)',
      type: 'string',
      description: 'e.g., "Jan 2023" - for display purposes',
    },
    {
      name: 'endDate',
      title: 'End Date (Display)',
      type: 'string',
      description: 'e.g., "Present" or "Dec 2024" - for display purposes',
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
      description: 'Brief description of your role and achievements',
    },
    {
      name: 'achievements',
      title: 'Key Achievements',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Bullet points of key achievements',
    },
    {
      name: 'images',
      title: 'Experience Images',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      description: 'Photos from this experience (team photos, work environment, etc.)',
    },
    {
      name: 'isFeatured',
      title: 'Featured on Main Page',
      type: 'boolean',
      description: 'Show this experience in the preview on the main page (max 3)',
      initialValue: false,
    },
    {
      name: 'order',
      title: 'Display Order',
      type: 'number',
      description: 'Lower number = appears first',
    },
  ],
  orderings: [
    {
      title: 'Display Order',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
    {
      title: 'By Start Year (Newest)',
      name: 'startYearDesc',
      by: [{ field: 'startYear', direction: 'desc' }],
    },
  ],
  preview: {
    select: {
      title: 'role',
      subtitle: 'company',
      media: 'companyLogo',
    },
  },
}
